-- 동물 테이블
-- 이름, 나이, 색

CREATE SEQUENCE SEQ_ANIMAL
START WITH 1
INCREMENT BY 10;
CREATE TABLE TBL_ANIMAL(
	ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
	ANIMAL_NAME VARCHAR2(255)UNIQUE NOT NULL,
	ANIMAL_AGE NUMBER DEFAULT 0,
	ANIMAL_COLOR VARCHAR2(255)
);

INSERT INTO TBL_ANIMAL
VALUES(SEQ_ANIMAL.NEXTVAL, '진도기', 5, '갈색');

INSERT INTO TBL_ANIMAL
VALUES(SEQ_ANIMAL.NEXTVAL, '치즈', 5, '주황색');

SELECT * FROM TBL_ANIMAL;
SELECT * FROM TBL_PET;

-- RENAME // 테이블 이름 변경
-- RENAME COLUMN // 테이블의 컬럼 이름 변경

ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO ANIMAL_SPECIES;
ALTER TABLE TBL_ANIMAL RENAME TO TBL_PET;

ALTER TABLE TAB_PET RENAME COLUMN ANIMAL_SPECIES TO PET_SPECIES;
ALTER TABLE TAB_PET RENAME COLUMN ANIMAL_SPE                  CIES TO PET_SPECIES;
ALTER TABLE TAB_PET RENAME COLUMN ANIMAL_SPECIES TO PET_SPECIES;

--시퀀스 이름변경
RENAME SEQ_ANIMAL TO SEQ_PET;

--PK키는 이름을 바꿀 수 없다.
--PK 키를 
ALTER TABLE TBL_PET DROP CONSTRAINT PK_ANIMAL;
ALTER TABLE TBL_PET ADD CONSTRAINT PK_PET PRIMARY KEY(ID);

CREATE TABLE TBL_PET(
	ID NUMBER,
	PET_NAME VARCHAR2(255)UNIQUE NOT NULL,
	PET_AGE NUMBER DEFAULT 0,
	PET_COLOR VARCHAR2(255),
	CONSTRAINT PK_PET PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_CAR
START WITH 1;
CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NAME VARCHAR2(255)UNIQUE NOT NULL,
	CAR_NUMBER NUMBER UNIQUE NOT NULL,
	CAR_BRAND VARCHAR2(255)UNIQUE NOT NULL,
	CAR_MADE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CAR_COLOR VARCHAR2(255),
	CAR_PRICE NUMBER
);
INSERT INTO TBL_CAR
VALUES(SEQ_CAR.NEXTVAL, 'FERRAI', 123456, '페라리', CURRENT_TIMESTAMP, 'RED', 300000);

SELECT * FROM TBL_CAR;

CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER
);

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	USER_ID NUMBER,
	CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);

-- 요구사항
-- 회사에서 광고를 신청하려고합니다.
-- 회사와 광고 테이블을 만들어주세요

CREATE SEQUENCE SEQ_COM;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COM_NAME VARCHAR2(255) NOT NULL,
	COM_EMPLOYEES NUMBER DEFAULT 1
);

CREATE SEQUENCE SEQ_AD;
CREATE TABLE TBL_AD(
	ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
	AD_NAME VARCHAR2(255) NOT NULL,
	AD_CONTENT VARCHAR(255) NOT NULL
);

CREATE SEQUENCE SEQ_ADVER_FORM;
CREATE TABLE TBL_ADVER_FORM(
	ID NUMBER CONSTRAINT PK_AD_FORM PRIMARY KEY,
	COM_ID NUMBER,
	CONSTRAINT FK_AD_COM FOREIGN KEY(COM_ID)
	REFERENCES TBL_COMPANY(ID),
	AD_ID NUMBER,
	CONSTRAINT FK_AD_COM FOREIGN KEY(AD_ID)
	REFERENCES TBL_AD(ID)
);

INSERT INTO TBL_COMPANY
VALUES(SEQ_COM.NEXTVAL, '웅진미디어', 6);

INSERT INTO TBL_COMPANY
VALUES(SEQ_COM.NEXTVAL, 'SOCAR', 470);

INSERT INTO TBL_AD
VALUES(SEQ_AD.NEXTVAL, '미디어는 웅진 미디어와 함께!', '복잡한 어쩌고는 웅진과 함께!', 1);


INSERT INTO TBL_AD
VALUES(SEQ_AD.NEXTVAL, '이젠 전기 자전거도 소카 일렉트로닉으로!', '전기 자전거 또한 소카로 빌릴 수 있어요!', 2);

SELECT * FROM TBL_COMPANY;
SELECT * FROM TBL_AD;



-- 요구사항
-- 회원이 존재하고 회원은 여러 상품을 구매할 수 있습니다. 중복 데이터를 막기 위해 중간 테이블이 있는 것
-- 데이터베이스 시스템을 만들어주세요.

-- 회원 / 중간 / 상품
CREATE SEQUENCE SEQ_CUSTOMER;
CREATE TABLE TBL_CUSTOMER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	CUSTOMER_NAME VARCHAR2(255) NOT NULL,
	CUSTOMER_PHONE VARCHAR2(255) NOT NULL,
	CUSTOMER_MONEY NUMBER DEFAULT 0
);
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_COUNT NUMBER DEFAULT 999
);
CREATE SEQUENCE SEQ_SELL;
CREATE TABLE TBL_SELL(
	ID NUMBER CONSTRAINT PK_SELL PRIMARY KEY,
	CUSTOMER_ID NUMBER,
	CONSTRAINT FK_SELL_CUSTOMER FOREIGN KEY(CUSTOMER_ID)
	REFERENCES TBL_CUSTOMER(ID),
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_SELL_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

-- 상품 판매자, 상품 구매자에게 배송을 할 수 있는 기능이 필요함
CREATE SEQUENCE SEQ_SELLER;
CREATE TABLE TBL_SELLER(
	ID NUMBER CONSTRAINT PK_SELL PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	DRINK_TYPE VARCHAR(255) NOT NULL,
	DRINK_HEGIHT NUMBER NOT NULL,
	MADE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER(
	ID NUMBER CONSTRAINT PK_BUYER PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	PHONE VARCHAR2(255) NOT NULL,
	ADRESS VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_DELEVERY;
CREATE TABLE TBL_DELEVERY(
	ID NUMBER CONSTRAINT PK_DELEVERY PRIMARY KEY,
	DELEVERY_STATUS CHAR(10),	
	DELEVERY_START TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DELEVERY_END TIMESTAMP,
	SELLER_ID NUMBER,
	CONSTRAINT FK_DELEVERY_SELLER FOREIGN KEY(SELLER_ID)
	REFERENCES TBL_SELLER(ID)
	BUYER_ID NUMBER,
	CONSTRAINT FK_DELEVERY_BUYER FOREIGN KEY(BUYER_ID)
	REFERENCES TBL_BUYER(ID)
);

CREATE SEQUENCE SEQ_GOODS_USER;
CREATE TABLE TBL_GOODS_USER(
	ID NUMBER CONSTRAINT PK_GOODS_USER PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	PHONE VARCHAR2(255) NOT NULL,
	ADRESS VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_GOODS;
CREATE TABLE TBL_GOODS(
	ID NUMBER CONSTRAINT PK_GOODS PRIMARY KEY,
	NAME VARCHAR2(255) NOT NULL,
	PRICE VARCHAR2(255) NOT NULL,
	GOODS_COUNT NUMBER DEFAULT 999,
	MAKE_PERIOD TIMESTAMP
);

CREATE SEQUENCE SEQ_GIFTS;
CREATE TABLE TBL_GIFTS(
	ID NUMBER CONSTRAINT PK_GIFTS PRIMARY KEY,
	USER_ID NUMBER,
	CONSTRAINT FK_DELEVERY_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_GOODS_USER(ID),
	GOODS_ID NUMBER,
	CONSTRAINT FK_DELEVERY_GOODS FOREIGN KEY(GOODS_ID)
	REFERENCES TBL_GOODS(ID),
	DELEVER_STATUS CHAR(10),
	DELEVER_START TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DELEVER_END TIMESTAMP
);




/*
요구사항
   유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
   아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
   체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
   아이들은 여러 번 체험학습에 등록할 수 있어요.
*/

CREATE SEQUENCE SEQ_CHILDREN;
CREATE TABLE TBL_CHILDREN(
	ID NUMBER CONSTRAINT PK_CHILDREN PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	AGE NUMBER NOT NULL,
	GENDER CHAR(10) NOT NULL
);
CREATE SEQUENCE SEQ_PARENTS;
CREATE TABLE TBL_PARENTS(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	AGE NUMBER NOT NULL,
	ADRESS VARCHAR(255) NOT NULL,
	PHONE VARCHAR(255) NOT NULL UNIQUE,
	GENDER CHAR(10) NOT NULL,
	CHILDREN_ID NUMBER,
	CONSTRAINT FK_CHIPAR_PARENTS FOREIGN KEY(CHILDREN_ID)
	REFERENCES TBL_CHILDREN(ID)
);

CREATE SEQUENCE SEQ_TRAVALS;
CREATE TABLE TBL_TRAVALS(
	ID NUMBER CONSTRAINT PK_TRAVALS PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	CONTENT VARCHAR(255) NOT NULL
);

CREATE SEQUENCE SEQ_TRAVALS_IMG;
CREATE TABLE TBL_TRAVALS_IMG(
	ID NUMBER CONSTRAINT PK_TRAVALS_IMG PRIMARY KEY,
	TRAVALS_ID NUMBER,
	CONSTRAINT FK_IMG_TRAVALS FOREIGN KEY (TRAVALS_ID)
	REFERENCES TBL_TRAVALS(ID),
	URL VARCHAR2(255)
);

CREATE SEQUENCE SEQ_TRAVAL_WRITHE;
CREATE TABLE TBL_WRITE(
	ID NUMBER CONSTRAINT PK_WRITHE PRIMARY KEY,
	TRAVAL_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	TRAVALS_ID NUMBER,
	CONSTRAINT FK_WRITE_TRAVALS FOREIGN KEY (TRAVALS_ID)
	REFERENCES TBL_TRAVALS(ID),
	CHILDREN_ID NUMBER,
	CONSTRAINT FK_WRITE_CHILDREN FOREIGN KEY (CHILDREN_ID)
	REFERENCES TBL_CHILDREN(ID)
);
*/

-- 회사
-- 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
   COMPANY_NAME VARCHAR2(255) NOT NULL,
   COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
   COMPANY_PHONE VARCHAR2(255),
   COMPANY_TYPE VARCHAR2(255) NOT NULL
   CONSTRAINT BAN_TYPE CHECK(COMPANY_TYPE IN ('스타트업', '중소기업', '중견기업', '대기업'))
);

-- 광고
CREATE SEQUENCE SEQ_ADVERTISEMENT;
CREATE TABLE TBL_ADVERTISEMENT(
   ID NUMBER CONSTRAINT PK_ADVERTISEMENT PRIMARY KEY,
   ADVERTISEMENT_TITLE VARCHAR2(255) NOT NULL,
   ADVERTISEMENT_CONTENT VARCHAR2(255) NOT NULL
);

-- 신청 FK
-- 대카테고리 FK
CREATE SEQUENCE SEQ_TBL_CATEGORY_A;
CREATE TABLE TBL_CATEGORY_A(
   ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
   CATEGORY_A_NAME VARCHAR2(255) NOT NULL,
   ADVERTISEMENT_ID NUMBER,
   CONSTRAINT FK_CATEGORY_A_ADVERTISEMENT FOREIGN KEY(ADVERTISEMENT_ID)
   REFERENCES TBL_ADVERTISEMENT(ID)
);

-- 중카테고리 FK
CREATE SEQUENCE SEQ_CATEGODY_B;
CREATE TABLE TBL_CATEGORY_B(
   ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
   CATEGORY_B_NAME VARCHAR2(255) NOT NULL,
   CATEGORY_A_ID NUMBER,
   CONSTRAINT FK_CATEGORY_B_CATEGOGY_A FOREIGN KEY(CATEGORY_A_ID)
   REFERENCES TBL_CATEGORY_A(ID)
);

-- 소카테고리 FK
CREATE SEQUENCE SEQ_CATEGORY_C;
CREATE TABLE TBL_CATEGORY_C(
   ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
   CATEGORY_B_ID NUMBER,
   CONSTRAINT FK_CATEGORY_C_CATEGORY_B FOREIGN KEY(CATEGORY_B_ID)
   REFERENCES TBL_CATEGORY_B(ID)
);

-- 신청 테이블
CREATE SEQUENCE SEQ_ADVERTISEMENT_APPLY;
CREATE TABLE TBL_ADVERTISEMENT_APPLY(
   ID NUMBER CONSTRAINT PK_ADVERTISEMENT_APPLY PRIMARY KEY,
   COMPANY_ID NUMBER,
   ADVERTISEMENT_ID NUMBER,
   CONSTRAINT FK_ADVERTISEMENT_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
   REFERENCES TBL_COMPANY(ID),
   CONSTRAINT FK_ADVERTISEMENT_APPLY_ADVERTISEMENT FOREIGN KEY(ADVERTISEMENT_ID)
   REFERENCES TBL_ADVERTISEMENT(ID)
);