SELECT TP.ID, TP.POST_TITLE, TU.USER_EMAIL
FROM TBL_POST tp
INNER JOIN TBL_USER tu
ON tp.USER_ID = tu.ID
ORDER BY ID DESC;

SELECT tr.REPLY_CONTEXT, tu.USER_EMAIL 
FROM TBL_REPLY tr 
INNER JOIN TBL_USER tu
ON tr.USER_ID = tu.ID
WHERE REPLY_CONTEXT LIKE '%한민%';

/*
 * SQL의 실행순서
 * FROM > JOIN > WHERE > GROUP BY > HAVING > SELECT > ORDER BY
 * 
 * 
 * 
 */

/*

구매자
상품
주문

*/

CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER(
	ID NUMBER CONSTRAINT PK_BUYER PRIMARY KEY,
	BUYER_NAME VARCHAR2(255) NOT NULL,
	BUYER_AGE NUMBER NOT NULL,
	BUYER_GENDER CHAR(10) CONSTRAINT BAN_GENDER CHECK(BUYER_GENDER IN ('남', '여')),
	BUYER_ADDRESS VARCHAR2(255),
	BUYER_PHONE VARCHAR2(255)
);
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCFT PRIMARY KEY,
	PRODUCT_BRAND VARCHAR2(255),
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER
);
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_STATE VARCHAR2(255) DEFAULT '배송대기' CONSTRAINT BAN_STATE CHECK(ORDER_STATE IN ('결제대기','결제완료','배송대기', '배송 중', '배송완료')),
	ORDER_START_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ORDER_END_DATE TIMESTAMP,
	BUYER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_BUYER FOREIGN KEY(BUYER_ID)
	REFERENCES TBL_BUYER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '짱구', 40, '남', '서울시 강남구', '010-3344-1234');

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '유리', 20, '여', '서울시 종로구', '010-7848-5656');

INSERT INTO TBL_BUYERS
VALUES (SEQ_BUYER.NEXTVAL, '맹구', 35, '남', '서울시 노원구', '010-1313-7854');

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '철수', 30, '남', '서울시 용산구', '010-5533-7711');

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '훈이', 20, '남', '경기도 남양주시', '010-1234-5678');

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '수지', 40, '여', '서울시 강북구', '010-4542-8753');

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '봉미선', 50, '서울시 강남구', '010-3456-7575');

INSERT INTO TBL_BUYER
VALUES (SEQ_BUYER.NEXTVAL, '이태희', 20, '서울시 스카이캐슬', '010-7345-1578');

SELECT TBO.ORDER_START_DATE, TBB.BUYER_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID;

SELECT TBU.*, TBP.PRODUCT_NAME
FROM (
	SELECT BUYER_ID, PRODUCT_ID
	FROM TBL_ORDER
	WHERE PRODUCT_ID IN (
		SELECT PRODUCT_ID
		FROM (
			SELECT PRODUCT_ID
			FROM TBL_ORDER
			GROUP BY PRODUCT_ID
			ORDER BY COUNT(PRODUCT_ID) DESC
		)
		WHERE ROWNUM = 1
	)
) TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT TBB.*, TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBP.ID = (
	SELECT PRODUCT_ID
	FROM (
		SELECT PRODUCT_ID
		FROM (
			SELECT PRODUCT_ID
			FROM TBL_ORDER
			GROUP BY PRODUCT_ID
			ORDER BY COUNT(PRODUCT_ID) DESC
		)
	)
	WHERE ROWNUM = 1
);

SELECT TBP.PRODUCT_NAME AS "상품명", TBP.PRODUCT_PRICE * TBO.COUNT_PRODUCT AS "총 매출액"
FROM (
	SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS "COUNT_PRODUCT"
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
) TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT COUNT(ID) AS "20~30대 구매자 수"
FROM TBL_BUYER
WHERE ID IN (
	SELECT BUYER_ID
	FROM TBL_ORDER
) 
AND BUYER_AGE >= 20 AND BUYER_AGE < 30;

SELECT TBB.BUYER_NAME AS "구매자 이름", TBB.BUYER_AGE AS "구매자 나이"
FROM (
	SELECT BUYER_ID
	FROM TBL_ORDER
	WHERE PRODUCT_ID = (
		SELECT ID
		FROM TBL_PRODUCT 
		WHERE PRODUCT_BRAND LIKE '%뉴발란스%'
	)
) TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
WHERE TBB.BUYER_AGE >= 20 AND TBB.BUYER_AGE <= 29;

SELECT BUYER_AGE, AVG(BUYER_AVG)
FROM (
	SELECT TBB.BUYER_ID, TBB.BUYER_AGE, SUM(TBP.PRODUCT_PRICE) AS "BUYER_AVG"
	FROM TBL_ORDER TBO
	JOIN (
		SELECT ID AS BUYER_ID, BUYER_NAME, BUYER_AGE, BUYER_GENDER
		FROM TBL_BUYER
		WHERE BUYER_GENDER LIKE '%여%'
	) TBB
	ON TBO.BUYER_ID = TBB.BUYER_ID
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	GROUP BY TBB.BUYER_ID, BUYER_AGE
)
GROUP BY BUYER_AGE;

SELECT SUM(TBO.PRODUCT_COUNT * TBP.PRODUCT_PRICE) AS "총 판매액수"
FROM (
	SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS "PRODUCT_COUNT"
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
) TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT TBB.BUYER_NAME, TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN (
	SELECT ID, PRODUCT_NAME, PRODUCT_TOTAL
	FROM (
		SELECT TBP.ID, TBP.PRODUCT_NAME, TBO.PRODUCT_COUNT * TBP.PRODUCT_PRICE AS "PRODUCT_TOTAL"
		FROM (
			SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS "PRODUCT_COUNT"
			FROM TBL_ORDER
			GROUP BY PRODUCT_ID
		) TBO
		JOIN TBL_PRODUCT TBP
		ON TBO.PRODUCT_ID = TBP.ID
		ORDER BY PRODUCT_TOTAL ASC
	)
	WHERE ROWNUM = 1
) TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID;

SELECT TBP.*, TBB.*
FROM TBL_ORDER TBO
JOIN (
	SELECT *
	FROM TBL_BUYER
	WHERE BUYER_ADDRESS LIKE '%경기도%'
) TBB
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT *
FROM TBL_PRODUCT
WHERE ID = (
	SELECT PRODUCT_ID
	FROM (
		SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS "PRODUCT_COUNT"
		FROM TBL_ORDER TBO
		JOIN (
			SELECT *
			FROM TBL_BUYER
			WHERE BUYER_GENDER LIKE '%남%' AND BUYER_AGE >= 30 AND BUYER_AGE < 40
		) TBB
		ON TBO.BUYER_ID = TBB.ID
		GROUP BY PRODUCT_ID
		ORDER BY PRODUCT_COUNT DESC
	)
	WHERE ROWNUM = 1
);

SELECT PRODUCT_NAME
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	HAVING COUNT(PRODUCT_ID) = (
		SELECT MIN(COUNT(PRODUCT_ID))
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
	)
);

SELECT TBP.PRODUCT_NAME, TBB.*
FROM TBL_ORDER TBO
JOIN (
	SELECT *
	FROM TBL_BUYER
	WHERE BUYER_AGE > (
		SELECT AVG(BUYER_AGE)
		FROM TBL_BUYER
	)
) TBB
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT TBP.PRODUCT_NAME, TBO.PRODUCT_COUNT
FROM (
	SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS "PRODUCT_COUNT"
	FROM TBL_ORDER TBO
	JOIN (
		SELECT *
		FROM TBL_BUYER
		WHERE BUYER_GENDER LIKE '%여%' AND BUYER_AGE >= 20 AND BUYER_AGE < 30
	) TBB
	ON TBO.BUYER_ID = TBB.ID
	GROUP BY PRODUCT_ID
) TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT *
FROM TBL_PRODUCT
WHERE ID IN (
	SELECT PRODUCT_ID
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	HAVING COUNT(PRODUCT_ID) = (
		SELECT MIN(COUNT(PRODUCT_ID))
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
	)
);