-- 유저 테이블 생성
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY, -- 아이디, 프라이머리(유일)키로서 중복 될 수 없으며, NULL 로도 지정될 수 없다.
	USER_NAME VARCHAR2(255), --USER_NAME 가변길이 문자열
	USER_AGE NUMBER, -- USER_AGE 정수
	USER_ADDRESS VARCHAR(255) --USER_ADDRESS 가변길이 문자열
);

-- 상품 PRODUCT
-- 상품 이름, 상품 가격, 상품 재고, 상품 설명

CREATE SEQUENCE SEQ_PRODUCT; -- 시퀀스 = 0부터 시작해서 메서드에 따라 늘어난다 ★ 강사님께 질문 예정
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY, -- 아이디, 정수, 제약조건,  프라이머리(유일)키로서 중복 될 수 없으며, NULL 로도 지정될 수 없다.
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL, -- 이름, 최대 255크기의 가변길이 문자열, (제약조건) 중복 불가, NULL로 저장할 수 없다. // 도메인 무결성
	PRODUCT_PRICE NUMBER NOT NULL, -- 가격, 정수, (제약조건) NULL로 저장할 수 없다.
	PRODUCT_COUNT NUMBER DEFAULT 999, -- 재고, 정수, 기본값 999
	PRODUCT_INFO VARCHAR2(255) -- 설명, 최대 255크기의 가변길이 문자열
);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE) -- INSERT - 해당 테이블에 정보 삽입, (아이디, 이름, 가격) - 넣을 정보 // 강사님께서 부연설명 예정
VALUES(SEQ_PRODUCT.NEXTVAL, '82세곽춘삼할아버지의마지막끌어치기', 50000); -- 정보에 들어갈 값 (SEQ_PRODUCT.NEXTVAL = i++)

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '일단 달리고 보는 최우빈의 전기자전거', 50000);

--DROP TABLE TBL_PRODUCT;
--DROP SEQUENCE SEQ_PRODUCT;

SELECT * FROM TBL_PRODUCT; -- 테이블 선택(전체 행)

ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER; -- 열 추가

ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0; -- 열 수정

ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT; -- 열 삭제

-- MEMBER 테이블
-- ID, 이름, 나이, 성별, 주소
-- ID는 시퀀스로 관리
-- 사용자를 2명 추가
-- 등급 컬럼 CHAR 타입으로 추가
-- 등급 컬럼을 VARCAHR2 타입으로 변경
-- 등급 컬럼 삭제

CREATE SEQUENCE SEQ_MEMBER; -- 시퀀스 설정
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY, -- 아이디, 프라이머리(유일)키로서 중복 될 수 없으며, NULL로도 지정될 수 없다.
	MEMBER_NAME VARCHAR2(255) UNIQUE NOT NULL, -- 이름, 최대 255크기의 가변길이 문자열, (제약조건) 중복 불가, NULL로 저정할 수 없다.
	MEMBER_AGE NUMBER NOT NULL, -- 나이, 정수, NULL로 저장할 수 없다.
	MEMBER_FEMALE_OF_MALE VARCHAR2(255) NOT NULL, -- 성별, 최대 255크기의 가변길이 문자열, (제약조건) NULL로 저장할 수 있다.
	MEMBER_ADRESS VARCHAR2(255) -- 주소, 최대 255크기의 가변길이 문자열
);

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_FEMALE_OF_MALE)
VALUES(SEQ_MEMBER.NEXTVAL, 'ㅇ^ㅇ', 22, 'MALE');
INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_FEMALE_OF_MALE)
VALUES(SEQ_MEMBER.NEXTVAL, 'ㅇ3ㅇ', 21, 'FEMALE');

ALTER TABLE TBL_MEMBER ADD MEMBER_GRADE CHAR(25);
ALTER TABLE TBL_MEMBER MODIFY MEMBER_GRADE VARCHAR(255);
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_GRADE;

SELECT * FROM TBL_MEMBER;