CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER,
	USER_ADDRESS VARCHAR(255)
);

-- 상품 PRODUCT
-- 상품 이름, 상품 가격, 상품 재고, 상품 설명

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_COUNT NUMBER DEFAULT 999,
	PRODUCT_INFO VARCHAR2(255)
);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '82세곽춘삼할아버지의마지막끌어치기', 50000);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '일단 달리고 보는 최우빈의 전기자전거', 50000);

--DROP TABLE TBL_PRODUCT;
--DROP SEQUENCE SEQ_PRODUCT;

SELECT * FROM TBL_PRODUCT;

ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;

ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;

-- MEMBER 테이블
-- ID, 이름, 나이, 성별, 주소
-- ID는 시퀀스로 관리
-- 사용자를 2명 추가
-- 등급 컬럼 CHAR 타입으로 추가
-- 등급 컬럼을 VARCAHR2 타입으로 변경
-- 등급 컬럼 삭제

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_FEMALE_OF_MALE VARCHAR2(255) NOT NULL,
	MEMBER_ADRESS VARCHAR2(255)
);

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_FEMALE_OF_MALE)
VALUES(SEQ_MEMBER.NEXTVAL, 'ㅇ^ㅇ', 22, 'MALE');
INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_FEMALE_OF_MALE)
VALUES(SEQ_MEMBER.NEXTVAL, 'ㅇ3ㅇ', 21, 'FEMALE');

ALTER TABLE TBL_MEMBER ADD MEMBER_GRADE CHAR(25);
ALTER TABLE TBL_MEMBER MODIFY MEMBER_GRADE VARCHAR(255);
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_GRADE;

SELECT * FROM TBL_MEMBER;